baseURL = "https://oscar845-s.github.io/PORTAFOLIO/"
languageCode = "es-mx"
title = "Portafolio"
theme = "ananke"

publishDir = "docs"

# Menú
[[menu.main]]
  name = "Prácticas"
  url = "/practicas/"
  weight = 2

[[menu.main]]
  name = "Principal"
  url = "/posts/"
  weight = 3
